salesforce_client_id: SALESFORCE_API_ID
salesforce_client_secret: SALESFORCE_API_SECRET

REDIS_URL: redis://localhost:6379/0/connector-salesforce

MNO_DEVPL_HOST: https://dev-platform.maestrano.io
⁠⁠⁠⁠MNO_DEVPL_API_PATH: /api/config/v1/marketplaces
MNO_DEVPL_ENV_NAME: connector-salesforce-uat
MNO_DEVPL_ENV_KEY: changeme
MNO_DEVPL_ENV_SECRET: changeme
