app_host: 'http://localhost:3001/'
environment: 'production'

encryption_key1: 'This is a key that is 256 bits!!'
encryption_key2: 'This is a key that is 256 bits!!'

default:
  api_host: 'https://maestrano.com'

maestrano-uat:
  api_host: 'https://uat.maestrano.io'
